[build]
  command = "pip install -r requirements.txt"
  publish = "static"

[build.environment]
  # Explicitly set the Python version to a supported one.
  PYTHON_VERSION = "3.11"

[dev]
  command = "streamlit run app.py"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
